[package]
name = "nextcore-tool"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
clap = { version = "4", features = ["derive"] }
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
plist = "1.10"
nextcore-core = { path = "../nextcore-core" }
nextcore-apls = { path = "../nextcore-apls" }
