#!/usr/bin/env python3
"""Verify actual BDIF recovery USB MMIO/DMA lifecycle using only generated bytes.

QEMU remains stopped (-S); no Apple firmware or guest instructions execute.
Run on Linux/WSL with the pinned QEMU patches. Temporary input disks are read-only.
"""
from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
import shutil
import socket
import struct
import subprocess
import sys
import tempfile
import time

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from venfire.artifacts import create_manifest, require_intact
from venfire.recovery import MAX_FRAME
from verify_barrier import VerificationError, check, emulator


CONTROL, QUEUE, COMMAND, BUSY = 0x30100404, 0x30100410, 0x30100408, 0x30100010
DESC, TARGET = 0x70001000, 0x70002000


def connect(path, deadline):
    client = socket.socket(socket.AF_UNIX)
    try:
        while True:
            remaining = deadline - time.monotonic()
            check(remaining > 0, "USB connection deadline expired")
            client.settimeout(remaining)
            try:
                client.connect(str(path))
                return client
            except (FileNotFoundError, ConnectionRefusedError):
                time.sleep(min(0.01, remaining))
    except BaseException:
        client.close()
        raise


def run_case(qemu, root, timeout):
    firmware = root / "own-halted-fixture.bin"
    firmware.write_bytes(b"26x86 QTEST\0\0\0")
    disks = []
    for name, size in (("aux", 64 << 20), ("root", 128 << 20)):
        disk = root / (name + ".raw")
        with disk.open("xb") as stream:
            stream.truncate(size)
        disks.append(disk)
    manifest = create_manifest([firmware, *disks])
    usbpath = root / "usb.sock"
    command = [qemu, "-M", "vmapple,research-headless=on,uuid=0",
               "-accel", "tcg,thread=single", "-cpu", "max,pauth=on,pauth-qarma5=on",
               "-m", "4G", "-smp", "2", "-bios", str(firmware), "-S",
               "-display", "none", "-monitor", "none", "-serial", "none",
               "-nic", "none", "-no-reboot", "-qtest", "stdio", "-qtest-log", "/dev/null",
               "-chardev", f"socket,id=vusb,path={usbpath},server=on,wait=off",
               "-global", "vmapple-bdif.usbdev=vusb"]
    for index, disk in enumerate(disks):
        view = "json:" + json.dumps({"driver": "raw", "read-only": True,
                                     "file": {"driver": "file", "filename": str(disk)}},
                                    separators=(",", ":"))
        command += ["-drive", f"if=pflash,index={index},readonly=on,file=" + view.replace(",", ",,")]
    checks = []

    def record(name, condition):
        checks.append({"name": name, "passed": bool(condition)})
        check(condition, name)

    try:
        require_intact(manifest)
        with emulator(command, root, timeout) as q:
            def post(capacity):
                q.memory_write(DESC, struct.pack("<QIHH", TARGET, capacity, 0, 2))
                q.write(QUEUE, 0, 4)
                q.write(COMMAND, DESC, 8)

            def completion():
                while True:
                    if q.read(BUSY, 4):
                        return True
                    check(time.monotonic() < q.deadline, "RX completion timed out")
                    time.sleep(0.001)

            record("disabled after device reset", q.read(CONTROL, 4) == 0)
            q.write(CONTROL, 1, 4)
            record("enable readback", q.read(CONTROL, 4) == 1)
            sentinel = b"\xcc" * 64
            q.memory_write(TARGET, sentinel)
            post(64)
            with connect(usbpath, q.deadline) as usb:
                usb.sendall(struct.pack("<I", 14) + b"abcde")
                time.sleep(0.02)
                q.write(CONTROL, 0, 4)
                record("disable completes with control zero", q.read(CONTROL, 4) == 0)
                record("disable disconnects partial old frame", usb.recv(1) == b"")
                record("disabled queue has no completion", q.read(BUSY, 4) == 0)
                record("partial old frame never DMA written", q.memory_read(TARGET, 64) == sentinel)
            q.write(CONTROL, 1, 4)
            with connect(usbpath, q.deadline) as usb:
                packet = b"new-owned-data"
                usb.sendall(struct.pack("<I", len(packet)) + packet)
                time.sleep(0.02)
                record("old RX ownership canceled across disable",
                       q.memory_read(TARGET, 64) == sentinel and q.read(BUSY, 4) == 0)
                post(64)
                completion()
                record("new descriptor receives exact current frame",
                       q.memory_read(TARGET, 64) == packet + sentinel[len(packet):])
                record("RX completion is consumed once", q.read(BUSY, 4) == 0)
                # Real iBSS recovery posts capacity 0x100006, unlike ROM's 0x80e.
                q.memory_write(TARGET, sentinel)
                post(MAX_FRAME)
                usb.sendall(struct.pack("<I", len(packet)) + packet)
                completion()
                record("iBSS 1 MiB plus header capacity accepts actual short frame",
                       q.memory_read(TARGET, 64) == packet + sentinel[len(packet):])
                q.memory_write(TARGET, sentinel)
                post(MAX_FRAME + 1)
                usb.sendall(struct.pack("<I", len(packet)) + packet)
                time.sleep(0.02)
                record("descriptor above supported capacity does not DMA or complete",
                       q.memory_read(TARGET, 64) == sentinel and q.read(BUSY, 4) == 0)
                q.write(CONTROL, 0, 4)
                record("second disable readback", q.read(CONTROL, 4) == 0)
            return {"checks": checks, "qtest_commands": q.commands,
                    "max_frame": MAX_FRAME, "generated_input_hashes": [
                        {"name": Path(a.path).name, "size_bytes": a.size_bytes, "sha256": a.sha256}
                        for a in manifest.artifacts], "inputs_unchanged": True}
    finally:
        require_intact(manifest)


def verify(qemu, timeout=15.0):
    check(sys.platform != "win32", "Run this verifier on Linux/WSL or another POSIX host")
    check(math.isfinite(timeout) and 1 <= timeout <= 30, "timeout must be between 1 and 30 seconds")
    executable = shutil.which(qemu)
    check(executable is not None, "QEMU executable not found")
    manifest = create_manifest([executable])
    executable = manifest.artifacts[0].path
    try:
        require_intact(manifest)
        with tempfile.TemporaryDirectory(prefix="venfire-recovery-") as temp:
            result = run_case(executable, Path(temp), timeout)
    finally:
        require_intact(manifest)
    result.update({"schema_version": 1, "layer": "QEMU BDIF USB device MMIO and DMA",
                   "passed": True, "guest_code_executed": False, "apple_assets_used": False,
                   "qemu": {"size_bytes": manifest.artifacts[0].size_bytes,
                            "sha256": manifest.artifacts[0].sha256},
                   "not_established": ["Apple firmware acceptance", "macOS boot",
                                       "bounded synchronous TX latency under peer backpressure"]})
    return result


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--qemu", required=True)
    parser.add_argument("--timeout", type=float, default=15.0)
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()
    try:
        if args.output and args.output.exists():
            raise ValueError("Output must be a new file")
        result = verify(args.qemu, args.timeout)
        content = json.dumps(result, indent=2) + "\n"
        if args.output:
            with args.output.open("x", encoding="utf-8", newline="\n") as stream:
                stream.write(content)
        print(content, end="")
        return 0
    except (OSError, ValueError, VerificationError, subprocess.SubprocessError) as exc:
        print(json.dumps({"passed": False, "error": str(exc)}), file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
